### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by Aloso** [rust-lang/foundation.rust-lang.org#34]
Spacing is all over the place. The header has a weird padding-bottom. Some things are centered, some are left-aligned, but the left-aligned sections have different paddings on the left. Spacing between sections is also rather arbitrary. The "Learn more about how we're different" and "Get in touch" buttons have slightly different heights. The aws logo looks much larger than the other ones. On the "members" page, the mozilla logo is wrapped on a new line on my screen, making it stand out. On mobile, the spacing is too large, some text is too large, some is too small or has a bad line height.

I'd be willing to help with these problems, if that's okay.

**Comment by ashleygwilliams** [comment]
Thanks for the offer! We'll be continuing to work on the website and I am willing to take some small changes but in general we don't have the personnel to support larger volunteer efforts at this time.

In general I would also encourage you to potentially file your issue with more empathetic language.

**Comment by Aloso** [comment]
I'm sorry about the language, I didn't mean to offend anyone. English is not my native language, so I sometimes find it difficult to get the tone right.

I hope you'll reconsider accepting contributions. I'm very excited about the foundation and would like to help, if only by making the website more accessible :)
